#!/bin/bash

alias be="bundle exec"
alias bs="bundle show"
alias gem="gem"
alias vundle="vim +BundleInstall +qall"

# for python
alias de="dae venv"
alias dja="django-admin.py"
alias djs="dj runserver"
alias djm="dj schemamigration --auto"
alias ipy='ipython3'
alias py='python'
alias pyvm="pythonbrew"

# for mysql
alias myschema='mysqldump -d'

# for utils
alias pkill='killall'
alias ls='ls --color=auto -X --group-directories-first'
alias gvim="gvim -f"
alias ll='ls -alF'
alias la='ls -A'
alias df='df -hT'
alias l='ls -CF'
alias open='gnome-open'
alias pgrep='pgrep -l'
alias ggrep='git grep -n'
alias untar='tar -zxvf'
alias cdr='while [ ! -d .git ] && [ ! `pwd` = "/" ] && [ ! `pwd` = ~ ]; do cd ..; done;'
alias so='source'
alias xclip='xclip -sel clip'
alias ssh-keygen-default='ssh-keygen -t rsa -C "me.ssword@gmail.com"'

alias t='time'
alias pyprof='python -m cProfile'
alias rbprof='ruby-prof'

alias ..='cd ..'

if [ "$KERNEL" = 'Darwin' ]; then
    alias ls='ls -G'
    alias ctags='/usr/local/Cellar/ctags/5.8/bin/ctags'
    unalias open
fi

