#!/bin/bash

# for utils
alias cdr='while [ ! -d .git ] && [ ! `pwd` = "/" ] && [ ! `pwd` = ~ ]; do cd ..; done;'
alias vi='nvim'
alias vim='nvim'
alias vsc='code'

alias untar-gz='tar xvfz'
alias untar-bz2='tar xvfj'
alias untar='tar xvf'
alias k='kubectl'

if [ "$KERNEL" = 'Darwin' ]; then
    # brew install coreutils
    alias ls='gls --color -h --group-directories-first --ignore={"*.pyc","__pycache__"}'
    # alias ctags='/usr/local/Cellar/ctags/5.8/bin/ctags'
    alias vsc="open -a 'Cursor'"
    alias mvim='open -a MacVim'
fi
