#!/usr/bin/env ruby
# https://gist.github.com/thbar/2423735

require 'rubygems'
require 'csv'
require 'awesome_print'

if STDIN.tty?
  puts 'your_command | csv'
else
  CSV.parse(STDIN.read, :headers => true) do |row|
    awesome_print row.to_hash
  end
end
