#!/bin/sh
# git-sub
# author: torpedoallen

# git grep完你是否很有replace的冲动？That's it.
#
# Install:
# 1. download it
# 2. put it in your $PATH
# 3. make it executable
# 4. enjoy it
#
# Usage: git sub old new

OLD=$1
NEW=$2

sed -e s/$OLD/$NEW/g -i.sbk $(git grep --files-with-match $OLD | xargs) && git ls-files --exclude-standard --others | grep -e '.*.sbk' --color=never | xargs rm
