#!/usr/bin/env ruby

require 'fileutils'

if ARGV.empty?
  puts 'usage: mcp-rename-version bnx2-2.78.11 bnx2i-2.7.8.1c'
else
  ARGV.each do |fn|
    if fn =~ /-\d+\.\d/
      target = fn.gsub(/(-|\.)/, '_')
      FileUtils.mv(fn, target)
    end
  end
end
