#!/usr/bin/env ruby
require 'thor'
require 'fileutils'

class CLI < Thor
  desc "vagrant", "start vagrant for dayjob"
  def vagrant
    FileUtils.chdir "#{ENV['HOME']}/work/shire-in-vagrant" do
      system "vagrant up &"
      system "vagrant ssh"
    end
  end

  desc "nightjob", "start vagrant for nightjob"
  def nightjob
    FileUtils.chdir "#{ENV['HOME']}/code/my-vagrant" do
      system "vagrant up &"
      system "vagrant ssh"
    end
  end
end

CLI.start(ARGV)
