#!/usr/bin/env ruby
require 'thor'
require 'fileutils'

class CLI < Thor
  desc "vagrant", "start vagrant, and mount its ~ into ~/vagrant"
  def vagrant
    FileUtils.chdir "#{ENV['HOME']}/work/shire-in-vagrant" do
      system "vagrant up &"
      system "vagrant ssh"
    end
  end
end

CLI.start(ARGV)
